models/LanguageModel.php
<?php


namespace app\admin\models;


use app\admin\services\LanguageTableService;
use yii\base\Model;

/**
 * Class LanguageModel
 * @package app\admin\models
 */
class LanguageModel extends Model
{
    /**
     * @var string
     */
    public $lang;

    /**
     * @var string
     */
    public $mainLangAlias;

    /**
     * @var string
     */
    public $file;


    /**
     * @return array
     */
    public function compareLangFilesWithBasic(): array
    {
        return [
            'status' => $this->getFileStatus(),
            'missingVariables' => $this->getFileMissingVariables(),
        ];
    }

    /**
     * @return array
     */
    private function getFileMissingVariables(): array
    {
        /** @var array $main */
        $main = include $this->mainLangAlias . '/' . LanguageTableService::RU . $this->file;

        if(!$this->checkFileExists() || !$current = include $this->mainLangAlias . '/' . $this->lang . $this->file) {
            return array_keys($main);
        }

        return $this->diffLangArrays($main, $current ?? []);
    }

    /**
     * @param array $main
     * @param array $current
     * @return array
     */
    private function diffLangArrays(array $main, array $current = []): array
    {
        $diff = [];

        foreach($main as $key => $value) {
            if(!isset($current[$key]) || $main[$key] === $current[$key]) {
                $diff[] = $key;
            }
        }

        return $diff;
    }

    /**
     * @return int
     */
    private function getFileStatus(): int
    {
        if(!$this->checkFileExists()) {
            return LanguageTableService::STATUS_MISSES;
        }

        return $this->getFileMissingVariables() ? LanguageTableService::STATUS_NOT_FULL : LanguageTableService::STATUS_EXISTS;
    }

    /**
     * @return bool
     */
    private function checkFileExists(): bool
    {
        return file_exists($this->mainLangAlias . '/' . $this->lang . $this->file);
    }
}

models/LoginForm.php
<?php

namespace app\admin\models;

/**
 * Class LoginForm
 */
class LoginForm extends \yii\base\Model
{
    public $username;
    public $password;


    public function rules()
    {
        return [
            [['username', 'password'], 'string'],
            [['username', 'password'], 'required'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'username' => 'Имя админа',
            'password' => 'Пароль',
        ];
    }
}

controllers/AuthController.php
<?php


namespace app\admin\controllers;


use app\admin\models\LoginForm;
use app\models\User;
use yii\filters\AccessControl;
use yii\web\Controller;

/**
 * Class AdminController
 * @package app\controllers
 */
class AuthController extends Controller
{
    public $layout = 'login';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['login', 'logout'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['logout'],
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }


    /**
     * Route /admin/auth/login/
     */
    public function actionLogin()
    {
        $model = new LoginForm();

        if ($model->load(\Yii::$app->request->post()) && $model->validate()) {
            if($admin = User::findUserByCredentials($model->username, $model->password)) {
                \Yii::$app->user->login($admin);

                $this->redirect(['site/index']);
            }
        }

        return $this->render('login', compact('model'));
    }

    /**
     * Route /admin/auth/logout/
     */
    public function actionLogout()
    {
        \Yii::$app->user->logout(true);

        return $this->redirect(['auth/login']);
    }

}

controllers/LangController.php
<?php


namespace app\admin\controllers;


use app\admin\services\LanguageTableService;
use yii\filters\AccessControl;
use yii\web\Controller;
use Yii;

/**
 * Class LangController
 * @package app\admin\controllers
 */
class LangController extends Controller
{
    public $layout = 'main';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'download', 'cron-clear-csv', 'cache-clear'],
                        'roles' => ['seeAdmin'],
                    ],
                ],
            ],
        ];
    }

    public function __construct($id, $module, $config = [])
    {
        \Yii::$app->user->loginUrl = ['admin/auth/login'];

        parent::__construct($id, $module, $config);
    }

    /**
     * Route /admin/
     */
    public function actionIndex()
    {
        $this->view->title = 'Language translations table';

        $langService = new LanguageTableService();

        $files = $langService->getFiles();

        return $this->render('index', compact('files'));
    }

    /**
     * Route /admin/lang-download
     *
     * @param string $lang
     * @param string $file
     * @param bool $mainFileDownload
     *
     * @return string
     */
    public function actionDownload(string $lang, string $file, bool $mainFileDownload = false)
    {
        $langService = new LanguageTableService();

        if(!$mainFileDownload) {
            if (file_exists($path = $langService->getLangFilePath($lang, $file))) {
                return \Yii::$app->response->sendFile($path, $langService->getFileName($file));
            }
        } else {
            if (file_exists($path = $langService->getLangFilePath($langService::RU, $file))) {
                return \Yii::$app->response->sendFile($path, $langService::getMainLang() . '_' . $langService->getFileName($file));
            }
        }

        return '';
    }


    /**
     * Роут занимается удалением временних файлов csv
     * из папки uploads/csv
     *
     * @author Grigor Grigoryan <grigor.g@kpigroups.com>
     */
    public function actionCronClearCsv()
    {
        $pathName = \Yii::$app->basePath . '/web/csv';

        $filesRemoved = false;

        Yii::$app->session->setFlash('FilesRemoved', 'The Folder Is Already Empty, Or Something Went Wrong');

        $countOfFiles = 0;

        if (file_exists($pathName)) {
            $files = glob($pathName . '/*');
            foreach ($files as $file) {
                if (is_file($file)) {
                    unlink($file);
                    $filesRemoved = true;
                    $countOfFiles++;
                }
            }
        }

        if($filesRemoved) {
            Yii::$app->session->setFlash('FilesRemoved', $countOfFiles . ' File(s) Removed Successfully');
        }

        return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);

    }

    /**
     * Роут для очистки кеша всего сайта
     *
     * @author Grigor Grigoryan <grigor.g@kpigroups.com>
     */
    public function actionCacheClear()
    {
        Yii::$app->cache->flush();

        return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
    }


}

controllers/SiteController.php
<?php


namespace app\admin\controllers;


use yii\filters\AccessControl;
use yii\web\Controller;

/**
 * Class AdminController
 * @package app\controllers
 */
class SiteController extends Controller
{
    public $layout = 'main';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index'],
                        'roles' => ['seeAdmin'],
                    ],
                ],
            ],
        ];
    }

    public function __construct($id, $module, $config = [])
    {
        \Yii::$app->user->loginUrl = ['admin/auth/login'];

        parent::__construct($id, $module, $config);
    }

    /**
     * Route /admin/
     */
    public function actionIndex()
    {
        $this->view->title = 'Home Page';
        return $this->render('index');
    }

}

views/lang/index.php
<?php
/**
 * @var \yii\web\View $this ;
 * @var array $files ;
 */

use app\admin\services\LanguageTableService;

$this->registerCssFile('/admin-files/libs/animate/animate.css');
$this->registerCssFile('/admin-files/libs/select2/select2.min.css');
$this->registerCssFile('/admin-files/libs/perfect-scrollbar/perfect-scrollbar.css');
$this->registerCssFile('/admin-files/css/util.css');
$this->registerCssFile('/admin-files/css/main-lang.css');


$this->registerJsFile('/admin-files/libs/bootstrap/js/popper.js', ['depends' => \yii\web\YiiAsset::class]);
$this->registerJsFile('/admin-files/libs/select2/select2.min.js', ['depends' => \yii\web\YiiAsset::class]);
$this->registerJsFile('/admin-files/js/main-lang.js', ['depends' => \yii\web\YiiAsset::class]);

?>


<div class="table100 ver2 m-b-110">
    <table data-vertable="ver2">
        <thead>
        <tr class="row100 head">
            <th class="column100 column1" data-column="column1">Page Path</th>
            <th class="column100 column2" data-column="column2">Ru</th>
            <?php $i = 3;
            foreach (LanguageTableService::getLangs() as $language) : ?>
                <th class="column100 column<?= $i ?>" data-column="column<?= $i ?>"><?= $language ?></th>
                <?php $i++; endforeach; ?>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($files as $file => $langs) : ?>
            <tr class="row100">
                <td class="column100 column1 <?= LanguageTableService::getFileFoldersStatus($langs) ?>" data-column="column1"><?= $file ?></td>
                <td class="column100 column2" data-column="column2">
                    <?= LanguageTableService::ICON_EXISTS ?>
                </td>
                <?php $i = 3;
                foreach (LanguageTableService::getLangs() as $language) : ?>
                    <td
                            data-lang="<?= $language ?>"
                            data-file="<?= $file ?>"
                            class="column100 column<?= $i ?> <?= LanguageTableService::getHtmlClassByType($langs[$language]['status']) ?>" data-column="column<?= $i ?>">
                        <?= LanguageTableService::getIconByType($langs[$language]['status']) ?>
                        <?= $this->render('sections/missing-variables', [
                                'missingVariables' => $langs[$language]['missingVariables'],
                                'status' => $langs[$language]['status']
                        ]) ?>
                    </td>
                    <?php $i++; endforeach; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

views/lang/sections/missing-variables.php
<?php

/**
 * @var int $status
 * @var array $missingVariables
 */

use app\admin\services\LanguageTableService;

?>

<?php if ($status === LanguageTableService::STATUS_NOT_FULL) : ?>
    <div class="not-full-hidden">
        <div class="alert-max">
            <?php foreach ($missingVariables as $missingVariable) : ?>
                <div><?= $missingVariable ?></div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>

views/layouts/login.php
<?php

use yii\helpers\Html;
use app\assets\AdminAsset;

AdminAsset::register($this)

?>

<?php $this->beginPage() ?>
    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <?= $this->render('@app/views/layouts/metricks/header'); ?>

        <?= Html::csrfMetaTags() ?>

        <title><?= Html::encode($this->title) ?></title>

        <?php if (Html::encode($this->metaDescription) != ''): ?>
            <meta name="description" content="<?= Html::encode($this->metaDescription); ?>">
        <?php endif ?>

        <?php if (Html::encode($this->metaKeywords) != ''): ?>
            <meta name="keywords" content="<?= Html::encode($this->metaKeywords); ?>">
        <?php endif ?>

        <?php $this->head() ?>
    </head>
    <body>

    <?php $this->beginBody() ?>
        <?= $content ?>
    <?php $this->endBody() ?>

    <?= $this->render('@app/views/layouts/metricks/footer'); ?>
    </body>
    </html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

use yii\helpers\Html;
use app\assets\AdminAsset;

AdminAsset::register($this)

?>

<?php $this->beginPage() ?>
    <!doctype html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <?= $this->render('@app/views/layouts/metricks/header'); ?>

        <?= Html::csrfMetaTags() ?>

        <title><?= Html::encode($this->title) ?></title>

        <?php if (Html::encode($this->metaDescription) != ''): ?>
            <meta name="description" content="<?= Html::encode($this->metaDescription); ?>">
        <?php endif ?>

        <?php if (Html::encode($this->metaKeywords) != ''): ?>
            <meta name="keywords" content="<?= Html::encode($this->metaKeywords); ?>">
        <?php endif ?>

        <?php $this->head() ?>
    </head>
    <body>

    <?php $this->beginBody() ?>

    <div class="page-wrapper chiller-theme toggled">

        <?= $this->render('../sections/sidebar'); ?>

        <main class="page-content">
            <div class="container-fluid">
                <?= Yii::$app->session->getFlash('FilesRemoved'); ?>
                <h2><?=$this->title ?></h2>
                <hr>
                <div class="row">
                    <div class="col-md-12">
                        <?= $content ?>
                    </div>
                </div>
            </div>
        </main>
    </div>
    <?php $this->endBody() ?>

    <?= $this->render('@app/views/layouts/metricks/footer'); ?>
    </body>
    </html>
<?php $this->endPage() ?>

views/sections/sidebar.php
<?php

use yii\helpers\Url;

/** @var \app\models\User $user */
$user = Yii::$app->user->identity;

?>

<a id="show-sidebar" class="btn btn-sm btn-dark" href="#">
    <svg class="bi bi-arrow-right-square" width="4em" height="4em" viewBox="-10 0 50 50" fill="currentColor"
         xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
              d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
        <path fill-rule="evenodd"
              d="M7.646 11.354a.5.5 0 0 1 0-.708L10.293 8 7.646 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0z"/>
        <path fill-rule="evenodd" d="M4.5 8a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1H5a.5.5 0 0 1-.5-.5z"/>
    </svg>
</a>
<nav id="sidebar" class="sidebar-wrapper">
    <div class="sidebar-content">
        <div class="sidebar-brand">
            <div id="close-sidebar">
                <svg class="bi bi-arrow-left-square" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
                     xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                          d="M14 1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                    <path fill-rule="evenodd"
                          d="M8.354 11.354a.5.5 0 0 0 0-.708L5.707 8l2.647-2.646a.5.5 0 1 0-.708-.708l-3 3a.5.5 0 0 0 0 .708l3 3a.5.5 0 0 0 .708 0z"/>
                    <path fill-rule="evenodd" d="M11.5 8a.5.5 0 0 0-.5-.5H6a.5.5 0 0 0 0 1h5a.5.5 0 0 0 .5-.5z"/>
                </svg>

            </div>
        </div>
        <div class="sidebar-header">
            <div class="user-pic">
                <a href="<?= Url::to(['site/index'])?>">
                    <img class="img-responsive img-rounded"
                         style="height: 50px;width:50px"
                         src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"
                     alt="User picture">
                </a>
            </div>
            <div class="user-info">
          <span class="user-name">
              <?= $user->name ?>
            <strong>
              [ <?= $user->username ?> ]
            </strong>
          </span>
                <span class="user-status">
                    <i class="fa fa-circle"></i>
                    <span>Online</span>
                </span>
            </div>
        </div>
        <!-- sidebar-header  -->

        <div class="sidebar-menu">
            <ul>
                <li class="header-menu">
                    <span>Components</span>
                </li>
                <li class="sidebar-dropdown">
                    <a href="#">
                        <svg class="bi bi-flag" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M3.5 1a.5.5 0 0 1 .5.5v13a.5.5 0 0 1-1 0v-13a.5.5 0 0 1 .5-.5z"/>
                            <path fill-rule="evenodd" d="M3.762 2.558C4.735 1.909 5.348 1.5 6.5 1.5c.653 0 1.139.325 1.495.562l.032.022c.391.26.646.416.973.416.168 0 .356-.042.587-.126a8.89 8.89 0 0 0 .593-.25c.058-.027.117-.053.18-.08.57-.255 1.278-.544 2.14-.544a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-.5.5c-.638 0-1.18.21-1.734.457l-.159.07c-.22.1-.453.205-.678.287A2.719 2.719 0 0 1 9 9.5c-.653 0-1.139-.325-1.495-.562l-.032-.022c-.391-.26-.646-.416-.973-.416-.833 0-1.218.246-2.223.916a.5.5 0 1 1-.515-.858C4.735 7.909 5.348 7.5 6.5 7.5c.653 0 1.139.325 1.495.562l.032.022c.391.26.646.416.973.416.168 0 .356-.042.587-.126.187-.068.376-.153.593-.25.058-.027.117-.053.18-.08.456-.204 1-.43 1.64-.512V2.543c-.433.074-.83.234-1.234.414l-.159.07c-.22.1-.453.205-.678.287A2.719 2.719 0 0 1 9 3.5c-.653 0-1.139-.325-1.495-.562l-.032-.022c-.391-.26-.646-.416-.973-.416-.833 0-1.218.246-2.223.916a.5.5 0 0 1-.554-.832l.04-.026z"/>
                        </svg>
                        <span>Languages</span>
                    </a>
                    <div class="sidebar-submenu">
                        <ul>
                            <li>
                                <a href="<?= Url::to(['lang/index'])?>">Compare data</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="sidebar-dropdown">
                    <a href="<?= Url::to(['lang/cron-clear-csv']) ?>">
                        <span>Clear archive files from disk</span>
                    </a>
                </li>
                <li class="sidebar-dropdown">
                    <a style="color:red" href="<?= Url::to(['lang/cache-clear']) ?>">
                        <span>Flush Cache</span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- sidebar-menu  -->
    </div>
    <!-- sidebar-content  -->
    <div class="sidebar-footer">
        <a href="#">
            <i class="fa fa-bell"></i>
            <span class="badge badge-pill badge-warning notification">3</span>
        </a>
        <a href="#">
            <i class="fa fa-envelope"></i>
            <span class="badge badge-pill badge-success notification">7</span>
        </a>
        <a href="#">
            <i class="fa fa-cog"></i>
            <span class="badge-sonar"></span>
        </a>
        <a href="<?= Url::to(['auth/logout'])?>">
            <i class="fa fa-power-off"></i>
        </a>
    </div>
</nav>
<!-- sidebar-wrapper  -->

views/site/index.php
<?php
/**
 * @var \yii\web\View $this ;
 */

?>